import assert from "node:assert/strict";
import { generateKeyPairSync, sign } from "node:crypto";
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve, sep } from "node:path";
import test from "node:test";

import { canonicalJson, validateCandidateDiff } from "../scripts/publication-contract.mjs";
import { contentManifest, editRegistry, editTodo, KEY_PATH, logoRollbackPlan, PARTNERS, planLogoFiles, REGISTRY_PATH, sha, TODO_PATH, validateCanonicalPng, validateGrant, validateLogoCandidate, validateReceipt } from "../scripts/partner-logo-contract.mjs";

const sourceRoot = resolve(import.meta.dirname, "..");
// Independently generated by Python's pinned RGBA stored-block encoder: two
// fabricated green pixels, no authentic partner art or email-derived bytes.
const PNG = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAIAAAABCAYAAAD0In+KAAAAFElEQVR4AQEJAPb/ABR4Mv8ooFD/DjcD1SSES2cAAAAASUVORK5CYII=", "base64");
const purpose = "partner_logo_execution_grant_v1";
const audience = "matthewart100-sys/backpackkidz/set_partner_logo";
const registry = readFileSync(join(sourceRoot, REGISTRY_PATH), "utf8");
const todo = readFileSync(join(sourceRoot, TODO_PATH), "utf8");
const item = (partner_id = "nicolas", classification = "synthetic_public_safe") => ({ partner_id, proposal_sha256: "a".repeat(64), decision_sha256: "b".repeat(64), candidate_ref: "synthetic-candidate-" + partner_id, custody_sha256: "c".repeat(64), classification, asset_sha256: sha(PNG), width: 2, height: 1, metadata: { alt: "Synthetic fixture pixels", layout: "" } });
const envelope = (payload, privateKey) => {
  const unsigned = { schema_version: 1, algorithm: "Ed25519", key_id: "ephemeral-test-key", payload };
  return { ...unsigned, signature: sign(null, Buffer.from(canonicalJson(unsigned)), privateKey).toString("base64url") };
};
const git = (root, ...args) => execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();

function fixture(t, classification = "synthetic_public_safe", partnerIds = ["nicolas"]) {
  const root = mkdtempSync(join(tmpdir(), "partner-logo-test-"));
  t.after(() => {
    const resolved = realpathSync(root);
    assert.ok(resolved.startsWith(realpathSync(tmpdir()) + sep) && basename(resolved).startsWith("partner-logo-test-"));
    rmSync(resolved, { recursive: true, force: true });
  });
  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  const now = Math.floor(Date.now() / 1000);
  const keys = [{ key_id: "ephemeral-test-key", purpose, public_key: publicKey.export({ format: "der", type: "spki" }).subarray(-32).toString("base64url"), not_before: now - 60, not_after: now + 3600 }];
  for (const path of [REGISTRY_PATH, TODO_PATH, "scripts/publication-contract.mjs", "scripts/partner-logo-contract.mjs", "scripts/partner-logo.mjs", "scripts/publication-shared.mjs"]) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    cpSync(join(sourceRoot, path), join(root, path));
  }
  mkdirSync(join(root, "publication"), { recursive: true });
  writeFileSync(join(root, KEY_PATH), canonicalJson({ schema: "partner_logo_execution_keys_v1", keys }) + "\n");
  writeFileSync(join(root, ".gitignore"), "node_modules/\n");
  git(root, "init", "-b", "main");
  git(root, "config", "user.name", "Synthetic fixture");
  git(root, "config", "user.email", "fixture@example.invalid");
  git(root, "config", "core.autocrlf", "false");
  git(root, "remote", "add", "origin", "https://github.com/matthewart100-sys/backpackkidz.git");
  git(root, "add", ".");
  git(root, "commit", "-m", "Synthetic isolated base");
  const base = { head: git(root, "rev-parse", "HEAD"), tree: git(root, "rev-parse", "HEAD^{tree}") };
  const items = partnerIds.map(id => item(id, classification));
  const files = planLogoFiles({ registry, todo, items, assets: new Map(items.map(i => [i.partner_id, PNG])) });
  const manifest = contentManifest(files);
  const payload = { purpose, audience, organization_id: "back-pack-kidz", workspace_id: "production", phase: "reserved", execution_id: "synthetic-execution-0001", run_id: "synthetic-run-0001", repository: "matthewart100-sys/backpackkidz", base, items, bundle_sha256: "d".repeat(64), bundle_decision_sha256: "e".repeat(64), manifest, issued_at: now, expires_at: now + 300 };
  const grant = envelope(payload, privateKey);
  const acknowledgement = envelope({ purpose, audience, organization_id: "back-pack-kidz", workspace_id: "production", phase: "materialized", execution_id: payload.execution_id, grant_sha256: sha(Buffer.from(canonicalJson(grant))), manifest_sha256: sha(Buffer.from(canonicalJson(manifest))), materialized_at: now, issued_at: now, expires_at: now + 300 }, privateKey);
  const receipt = { schema: "partner_logo_receipt_v1", grant, materialization: acknowledgement };
  const receiptPath = `publication/audit/partner-logo-${payload.bundle_sha256}.json`;
  git(root, "switch", "-c", "pilot/partner-logos-" + payload.bundle_sha256);
  function writeCandidate() {
    for (const [path, data] of files) { mkdirSync(dirname(join(root, path)), { recursive: true }); writeFileSync(join(root, path), data); }
    mkdirSync(dirname(join(root, receiptPath)), { recursive: true });
    writeFileSync(join(root, receiptPath), canonicalJson(receipt) + "\n");
    git(root, "add", ".");
    git(root, "commit", "-m", "Synthetic exact candidate");
    return git(root, "rev-parse", "HEAD");
  }
  return { root, now, privateKey, keys, grant, receipt, receiptPath, files, base, writeCandidate };
}

test("Python-produced canonical PNG is accepted and every structural mutation fails", () => {
  assert.equal(validateCanonicalPng(PNG, 2, 1).sha256, sha(PNG));
  assert.throws(() => validateCanonicalPng(PNG, 1, 2));
  assert.throws(() => validateCanonicalPng(Buffer.concat([PNG, Buffer.from("<script>")]), 2, 1));
  const bad = Buffer.from(PNG); bad[45] ^= 1;
  assert.throws(() => validateCanonicalPng(bad, 2, 1));
  assert.throws(() => validateCanonicalPng(Buffer.from("<svg/>"), 2, 1));
});

test("one partner edit preserves URLs, other records and unresolved TODO", () => {
  const result = editRegistry(registry, [item()]);
  assert.match(result, /image: "\/assets\/partner-nicolas-canonical.png"/u);
  assert.ok(result.includes(PARTNERS.nicolas.href) && result.includes(PARTNERS["studio-seven"].href));
  const updatedTodo = editTodo(todo, result);
  assert.match(updatedTodo, /approved logo file for Studio Seven PG/u);
  assert.equal(editRegistry(registry.replace(/\r\n/gu, "\n"), [item()]).replace(/\n/gu, "\r\n"), result.replace(/\r?\n/gu, "\r\n"));
});

test("two-item bundle changes exactly the registry, TODO and two fixed assets", () => {
  const items = [item(), item("studio-seven")];
  const files = planLogoFiles({ registry, todo, items, assets: new Map(items.map(i => [i.partner_id, PNG])) });
  assert.deepEqual([...files.keys()].sort(), [REGISTRY_PATH, TODO_PATH, PARTNERS.nicolas.asset, PARTNERS["studio-seven"].asset].sort());
  assert.ok(!files.get(TODO_PATH).toString().includes("TODO (owner): Provide approved logo files"));
});

test("arbitrary records, URLs, paths, script expressions and ambiguous declarations fail", () => {
  for (const changed of [
    { ...item(), partner_id: "unknown" },
    { ...item(), path: "../private" },
    { ...item(), href: "https://attacker.invalid" },
    { ...item(), metadata: { alt: "<img src=x>", layout: "" } },
    { ...item(), metadata: { alt: "Logo", layout: "arbitrary-class" } },
  ]) assert.throws(() => editRegistry(registry, [changed]));
  for (const source of [
    registry + "\nfunction extra(){ const communityPartners=[]; }",
    registry.replace('name: "Nicola\'s Italian Kitchen",', 'name: "Nicola\'s Italian Kitchen", name: "duplicate",'),
    registry.replace('name: "Nicola\'s Italian Kitchen",', 'name: "Nicola\'s Italian Kitchen", ...other,'),
    registry.replace('name: "Nicola\'s Italian Kitchen",', 'name: "Nicola\'s Italian Kitchen", image: runCode(),'),
    registry.replace(PARTNERS.nicolas.href, "https://attacker.invalid/"),
  ]) assert.throws(() => editRegistry(source, [item()]));
});

test("no caller key, altered purpose, missing bundle decision, or expired first execution", (t) => {
  const f = fixture(t);
  assert.equal(validateGrant(f.grant, f.keys, f.now).phase, "reserved");
  assert.throws(() => validateGrant(f.grant, [], f.now));
  assert.throws(() => validateGrant(f.grant, f.keys, f.now + 301));
  for (const replacement of [{ purpose: "structured_qualification" }, { bundle_decision_sha256: null }, { repository: "Other/repository" }, { items: [{ ...item(), classification: "public_safe" }] }]) {
    const changed = envelope({ ...f.grant.payload, ...replacement }, f.privateKey);
    assert.throws(() => validateGrant(changed, f.keys, f.now));
  }
  assert.equal(validateReceipt(f.receipt, f.keys).execution_id, "synthetic-execution-0001");
});

test("signed synthetic exact candidate passes preview and deliberately fails required publication check", (t) => {
  const f = fixture(t);
  const head = f.writeCandidate();
  assert.equal(validateLogoCandidate(f.root, { base: f.base.head, head, preview: true }).status, "passed");
  assert.throws(() => validateCandidateDiff(f.root, { base: f.base.head, head }), /synthetic_candidate_not_publishable/u);
});

test("authorized-class fixture supports exact candidate verification, retaining separate human merge authority", (t) => {
  const f = fixture(t, "authorized_public_sponsor", ["nicolas", "studio-seven"]);
  const head = f.writeCandidate();
  assert.equal(validateCandidateDiff(f.root, { base: f.base.head, head }).mode, "partner-logo-publication-candidate");
  assert.ok(!Object.hasOwn(f.receipt, "publicationDecision"));
});

test("candidate verifier rejects any extra file outside the signed manifest", (t) => {
  const f = fixture(t);
  f.writeCandidate();
  writeFileSync(join(f.root, "unauthorized.txt"), "outside the manifest");
  git(f.root, "add", "."); git(f.root, "commit", "-m", "Tamper fixture");
  assert.throws(() => validateLogoCandidate(f.root, { base: f.base.head, head: git(f.root, "rev-parse", "HEAD"), preview: true }), /unintended_diff/u);
});

test("real materializer IPC produces the same canonical files and receipt without publication", (t) => {
  const f = fixture(t);
  mkdirSync(join(f.root, "node_modules"), { recursive: true });
  cpSync(join(sourceRoot, "node_modules/acorn"), join(f.root, "node_modules/acorn"), { recursive: true });
  const run = (command, value) => JSON.parse(execFileSync(process.execPath, [join(f.root, "scripts/partner-logo.mjs"), command], { cwd: f.root, input: canonicalJson(value), encoding: "utf8" }));
  const materialized = run("materialize-files", { grant: f.grant, assets: { nicolas: PNG.toString("base64") } });
  assert.deepEqual(materialized.manifest, f.grant.payload.manifest);
  const attached = run("attach-receipt", { receipt: f.receipt });
  assert.equal(attached.receipt_path, f.receiptPath);
  assert.equal(readFileSync(join(f.root, PARTNERS.nicolas.asset)).equals(PNG), true);
  assert.equal(git(f.root, "rev-parse", "HEAD"), f.base.head);
  assert.deepEqual(run("materialize-files", { grant: f.grant, assets: { nicolas: PNG.toString("base64") } }).manifest, materialized.manifest);
  assert.deepEqual(run("attach-receipt", { receipt: f.receipt }), attached);
  assert.throws(() => run("merge", {}));
});

for (const mutation of ["pixels", "classification", "base", "metadata", "signature", "mode"]) {
  test(`immutable candidate rejects ${mutation} tampering`, t => {
    const f = fixture(t);
    f.writeCandidate();
    if (mutation === "pixels") {
      const pixels = Buffer.from(PNG); pixels[45] ^= 1;
      writeFileSync(join(f.root, PARTNERS.nicolas.asset), pixels);
    } else if (mutation === "mode") {
      git(f.root, "update-index", "--chmod=+x", PARTNERS.nicolas.asset);
    } else {
      const receipt = structuredClone(f.receipt);
      if (mutation === "classification") receipt.grant.payload.items[0].classification = "authorized_public_sponsor";
      if (mutation === "base") receipt.grant.payload.base.head = "0".repeat(40);
      if (mutation === "metadata") receipt.grant.payload.items[0].metadata.alt = "Unreviewed text";
      if (mutation === "signature") receipt.grant.signature = "a".repeat(86);
      writeFileSync(join(f.root, f.receiptPath), canonicalJson(receipt) + "\n");
    }
    if (mutation !== "mode") git(f.root, "add", ".");
    git(f.root, "commit", "-m", "Synthetic adversarial mutation");
    assert.throws(() => validateLogoCandidate(f.root, { base: f.base.head, head: git(f.root, "rev-parse", "HEAD"), preview: true }));
  });
}

test("human rollback reconstructs the immutable original files through a new bounded receipt", t => {
  const f = fixture(t, "authorized_public_sponsor", ["nicolas", "studio-seven"]);
  const published = f.writeCandidate();
  const plan = logoRollbackPlan(f.root, published, f.grant.payload.bundle_sha256);
  assert.equal(git(f.root, "status", "--porcelain"), "");
  for (const [path, bytes] of plan.restore) {
    if (bytes === null) unlinkSync(join(f.root, path));
    else writeFileSync(join(f.root, path), bytes);
  }
  writeFileSync(join(f.root, plan.receiptPath), canonicalJson(plan.receipt) + "\n");
  git(f.root, "add", "."); git(f.root, "commit", "-m", "Synthetic governed inverse");
  const head = git(f.root, "rev-parse", "HEAD");
  assert.equal(validateLogoCandidate(f.root, { base: published, head }).mode, "partner-logo-human-rollback-candidate");
  assert.equal(readFileSync(join(f.root, REGISTRY_PATH), "utf8").replace(/\r\n/gu, "\n"), registry.replace(/\r\n/gu, "\n"));
  assert.equal(existsSync(join(f.root, PARTNERS.nicolas.asset)), false);
});

test("rollback refuses changed current targets, synthetic publication and caller restore refs", t => {
  const synthetic = fixture(t);
  const syntheticHead = synthetic.writeCandidate();
  assert.throws(() => logoRollbackPlan(synthetic.root, syntheticHead, synthetic.grant.payload.bundle_sha256), /synthetic_candidate_not_publishable/u);
  const f = fixture(t, "authorized_public_sponsor");
  f.writeCandidate();
  writeFileSync(join(f.root, REGISTRY_PATH), readFileSync(join(f.root, REGISTRY_PATH), "utf8") + "\n// independent later change\n");
  git(f.root, "add", "."); git(f.root, "commit", "-m", "Synthetic subsequent target change");
  assert.throws(() => logoRollbackPlan(f.root, git(f.root, "rev-parse", "HEAD"), f.grant.payload.bundle_sha256), /target_changed/u);
  assert.throws(() => logoRollbackPlan(f.root, "main; arbitrary command", f.grant.payload.bundle_sha256));
});
